trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform
  jobs:
  - job: Deploy
    steps:
    - task: Checkout@1

    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - script: terraform init
      displayName: Terraform Init

    - script: terraform plan
      displayName: Terraform Plan

    - script: |
        pip install checkov
        checkov -d .
      displayName: Run Checkov

    - script: terraform apply -auto-approve
      displayName: Terraform Apply
